training:
  gpu_device: 0
  batch_size: 32
  num_workers: 4
  seed: 42
  lr: 2.e-4 # 1.e-4
  weight_decay: 1.e-2
  max_epochs: 100 # 80
  warm_epochs: 10
  patience: 20
  lr_scheduler: cosine
  lr_decay_steps: 100 # 80
  lr_decay_rate: 0.5
  lr_decay_min_lr: 1.e-6
  pretrained_model: logs/tcr-pmhc-binding-subsample-2/checkpoint.pt
  log_dir: logs/tcr-pmhc-cond-dplm-cross-attn-finetune-tcr-dplm-all-constant
  use_pmhc_struc_feat: False # True
  num_diffusion_steps: 100 # 100
  max_iter: 10 # will it improve by adding iterations?
  temperature: 0.1 # use lower temperature for gumbel argmax later
  sampling_strategy:  argmax # gumbel_argmax
  timestep_weighting: constant # linear
  partial_chain_prob: 0.4

model:
  tcr_model:
    num_layers: 6
    dim_head: 32 
    num_attn_heads: 8 
    dim: 256
    dropout: 0.1
    max_seq_len: 26
    use_cdr12_features: True # False
  pmhc_model:
    num_transformer_layers: 6
    transformer_attn_dim_head: 32
    transformer_attn_heads: 8
    dim_single: 256 
    dim_pairwise: 64
    pair_bias_attn_dim_head: 32
    pair_bias_attn_heads: 8
    tri_attn_dim_head: 16
    tri_attn_heads: 4
    dropout: 0.1
    max_pep_len: 26
    max_mhc_len: 175
    dim_mhc_in: 20
    pair_method: attention
    num_cnn_layers: 4
  adapter:
    dim_single: 256 
    dim_pairwise: 64
    pair_bias_attn_dim_head: 32
    pair_bias_attn_heads: 8
    tri_attn_dim_head: 16
    tri_attn_heads: 4
    dropout: 0.1
    pair_method: attention
    
data: 
  train_data_path: data/tcrpmhc/subsample/train_pos_data_subsampled.csv
  val_data_path: data/tcrpmhc/subsample/validation_pos_data.csv
  test_data_path: data/tcrpmhc/subsample/immrep23_test_pos_data.csv
  mhc_lib_path: data/pmhc/mhc_lib.json
  v_gene_lib_path: data/tcrpmhc/v_gene_lib.csv
  max_cdr3_len: 25
  max_peptide_len: 25
  max_mhc_len: 175
